const fs=require('fs'),path=require('path'),assert=require('assert/strict'),{webcrypto}=require('crypto');
const moduleRoot=process.env.RATIB_TEST_MODULE_ROOT||(fs.existsSync(path.resolve(__dirname,'../node_modules'))?path.resolve(__dirname,'../node_modules'):path.resolve(__dirname,'../../test-runtime/node_modules'));
const {JSDOM,VirtualConsole}=require(path.join(moduleRoot,'jsdom')),{IDBFactory}=require(path.join(moduleRoot,'fake-indexeddb'));
require('../licensing/protocol.js');const P=global.RatibLicenseProtocol,results=[],fixtures=[],root=path.resolve(__dirname,'..'),originalIds=JSON.parse(fs.readFileSync(__dirname+'/baseline-controls.json','utf8'));
const source=fs.readFileSync(root+'/index.html','utf8'),base=Date.now();let pair,config;
async function waitFor(fn,label){for(let i=0;i<600;i++){if(fn())return;await new Promise(r=>setTimeout(r,10));}throw Error('Timeout: '+label);}
async function test(name,fn){await fn();results.push(name);console.log('PASS',name);}
const script=s=>s.replace(/<\/script/gi,'<\\/script');
function make({idb=new IDBFactory(),seed={},offline=true,setup=false}={}){
 let now=base,networkCalls=[];const errors=[],downloads=[],logs=[],vc=new VirtualConsole();vc.on('jsdomError',e=>errors.push(e.message));vc.on('error',(...args)=>logs.push(args.map(x=>x?.stack||String(x)).join(' ')));
 let html=source.replace(/<script src="\.\/licensing\/(config|protocol|client)\.js"><\/script>/g,(_,name)=>'<script>'+script(name==='config'?'window.RATIB_LICENSE_CONFIG='+JSON.stringify(setup?{...config,endpoint:'',issuer:'',publicKeys:{}}:config):fs.readFileSync(root+'/licensing/'+name+'.js','utf8'))+'</script>');
 const dom=new JSDOM(html,{url:'https://app.test/Ratib0129/',runScripts:'dangerously',pretendToBeVisual:true,virtualConsole:vc,beforeParse(w){
  w.Date.now=()=>now;for(const [k,v]of Object.entries(seed))w.localStorage.setItem(k,v);
  Object.defineProperty(w,'crypto',{value:webcrypto});Object.defineProperty(w,'indexedDB',{value:idb});Object.defineProperty(w.navigator,'onLine',{value:!offline,configurable:true});
  w.TextEncoder=TextEncoder;w.TextDecoder=TextDecoder;w.structuredClone=structuredClone;w.Blob=Blob;w.File=File;w.AbortController=AbortController;
  w.alert=()=>{};w.confirm=()=>true;w.prompt=()=>null;w.scrollTo=()=>{};w.HTMLElement.prototype.scrollIntoView=()=>{};w.HTMLElement.prototype.scrollTo=()=>{};
  w.Notification=function(){};w.Notification.permission='denied';
  w.HTMLCanvasElement.prototype.getContext=function(){return {measureText:x=>({width:String(x).length*10}),fillText(){},fillRect(){},strokeRect(){},drawImage(){},beginPath(){},moveTo(){},lineTo(){},stroke(){}};};w.HTMLCanvasElement.prototype.toDataURL=()=> 'data:image/jpeg;base64,/9j/2Q==';
  const blobs=new Map();w.URL.createObjectURL=b=>{const key='blob:test-'+blobs.size;blobs.set(key,b);return key;};w.URL.revokeObjectURL=()=>{};w.HTMLAnchorElement.prototype.click=function(){downloads.push({name:this.download,blob:blobs.get(this.href)});};
  w.fetch=async(url,opts)=>{networkCalls.push({url,body:opts?.body});if(offline)throw Error('Offline');const req=await P.verifyRequest(JSON.parse(opts.body).requestCode);return Response.json({token:await signed(req.device,{kind:'trial',id:'TRIAL-'+req.device,startsAt:base,expiresAt:base+3*86400000,issuedAt:now,serverAt:now})});};
 }});
 const f={dom,w:dom.window,idb,errors,logs,downloads,networkCalls,setTime:x=>now=x,getTime:()=>now};fixtures.push(f);return f;
}
async function boot(f){await f.w.RatibLicense.ready;await waitFor(()=>f.w.eval('typeof selDebitAcc!=="undefined"&&!!selDebitAcc'),'financial app initialization');assert.deepEqual(f.errors,[],JSON.stringify(f.logs));await f.w.eval('flushStorage()');}
async function signed(device,extra={}){return P.signToken({v:1,aud:'ratib',iss:config.issuer,id:'LIC-test',device,kind:'annual',binding:'device',email:'',emailVerified:false,maxDevices:1,startsAt:base-1000,expiresAt:base+365*86400000,issuedAt:base,serverAt:base,revision:1,status:'active',...extra},pair.privateKey,'test-key');}
async function activate(f,extra){const request=await P.verifyRequest(await f.w.RatibLicense.requestCode(''));await f.w.RatibLicense.accept(await signed(request.device,extra));return request.device;}
const value=(f,expression)=>f.w.eval(expression);
const snapshot=f=>JSON.stringify(value(f,'_snapshotMemStore()'));
const sharedData={month:new Date(base).toISOString().slice(0,7),transactions:[{id:'synthetic-1',amount:100,currency:'YER',status:'posted',voucherMode:'spend',debitAccount:'الرواتب الأساسية والبدلات',creditAccount:'صندوق النقدية الرئيسي',seqNum:1,isoDate:'2026-10-01',date:'2026-10-01',distribution:{general:{id:'general',name:'عام',amount:100,color:'#64748b'}},execution:{general:{done:true,actualSpent:100,note:'synthetic test'}},schemaVersion:3}]};
(async()=>{try{
 pair=await webcrypto.subtle.generateKey({name:'ECDSA',namedCurve:'P-256'},false,['sign','verify']);config={endpoint:'https://license.test',issuer:'https://license.test',publicKeys:{'test-key':P.publicJwk(await webcrypto.subtle.exportKey('jwk',pair.publicKey))},clockToleranceMs:300000,syncIntervalMs:900000};
 await test('Existing UI controls and financial storage schema preserved',async()=>{const b=new JSDOM(source);const ids=[...b.window.document.querySelectorAll('[id]')].map(x=>x.id);for(const id of originalIds)assert(ids.includes(id));assert.equal(ids.length,new Set(ids).size);assert(source.includes("APP_STORAGE_PREFIX = 'masar_'"));assert(source.includes('APP_SCHEMA_VERSION = 3'));b.window.close();});
 const f=make({seed:{masar_plan:JSON.stringify(sharedData)}});await boot(f);
 await test('Offline first start does not invent a trusted trial',async()=>{assert.equal(f.w.RatibLicense.current().state,'unactivated');assert.equal(f.w.RatibLicense.current().writable,false);assert.equal(f.networkCalls.length,0);});
 await test('Expired or unactivated financial writes rejected without modifying data',async()=>{const before=snapshot(f);assert.throws(()=>value(f,"store.set('plan',{transactions:[]})"),/LICENSE_READ_ONLY/);assert.throws(()=>value(f,"store.remove('history')"),/LICENSE_READ_ONLY/);const copy=value(f,"store.get('plan',null)");copy.transactions.splice(0);assert.equal(snapshot(f),before);});
 await test('Blocked commit, reversal, and legacy import leave existing vouchers intact',async()=>{const before=snapshot(f);await value(f,'commitMultiVoucher()');await value(f,'applyLegacyImport()');value(f,"reverseTransactionById('synthetic-1')");assert.equal(snapshot(f),before);assert.equal(f.w.document.getElementById('ratibLicenseModal').hidden,false);f.w.RatibLicense.close();});
 await test('Viewing reports and financial backup export remain available',async()=>{value(f,'updateProDashboard();runBudgetReport();runAccountStatement()');const data=await value(f,'buildBackupPayload()');assert.equal(data.data.masar_plan.transactions[0].id,'synthetic-1');assert(!JSON.stringify(data).includes('RATIB1.'));assert(!JSON.stringify(data).includes('privateKey'));await value(f,'exportBackupFile()');assert(f.downloads.some(x=>x.name.endsWith('.json')));});
 await test('Device request signed locally and private key not exportable',async()=>{const code=await f.w.RatibLicense.requestCode('person@example.test'),req=await P.verifyRequest(code);assert.equal(req.email,'person@example.test');assert(!req.publicKey.d);const db=await new Promise((resolve,reject)=>{const q=f.idb.open('ratib_license_v1');q.onsuccess=()=>resolve(q.result);q.onerror=reject;});const identity=await new Promise(resolve=>{db.transaction('state').objectStore('state').get('identity').onsuccess=e=>resolve(e.target.result)});assert.equal(identity.privateKey.extractable,false);db.close();});
 let device;await test('Offline trial activation verifies, saves, and unlocks edits',async()=>{device=await activate(f,{kind:'trial',id:'TRIAL-test',expiresAt:base+3*86400000});assert.equal(f.w.RatibLicense.current().writable,true);assert.equal(f.w.RatibLicense.current().days,3);assert.equal(f.networkCalls.length,0);});
 await test('Actual cash voucher can save with active license and remain balanced',async()=>{value(f,"navigateToTab('pageExpenses');selectVoucherTypeDirect('spend');multiSourceAcc.setValue('صندوق النقدية الرئيسي','صندوق النقدية الرئيسي');document.getElementById('multiVoucherBaseCurrency').value='YER';multiVoucherLines[0].account='الرواتب الأساسية والبدلات';multiVoucherLines[0].amount=200;multiVoucherLines[0].currency='YER';renderMultiVoucherLines()");assert.equal(value(f,'validateMultiVoucher()'),'');await value(f,'commitMultiVoucher()');assert.equal(value(f,'getAllTransactions().length'),3);});
 const financialAfterSave=snapshot(f);await f.w.RatibLicense.checkpoint();const local=Object.fromEntries(Object.keys(f.w.localStorage).map(k=>[k,f.w.localStorage.getItem(k)]));f.w.close();
 const updated=make({idb:f.idb,seed:local});await boot(updated);
 await test('Offline reboot and updated app preserve license identity and financial data',async()=>{assert.equal(updated.w.RatibLicense.current().writable,true);assert.equal((await P.verifyRequest(await updated.w.RatibLicense.requestCode(''))).device,device);assert.equal(snapshot(updated),financialAfterSave);assert.equal(updated.networkCalls.length,0);});
 await test('Trial expires at three days and retains all vouchers and account data',async()=>{updated.setTime(base+3*86400000+10);assert.equal(updated.w.RatibLicense.current().state,'expired');const before=snapshot(updated);await value(updated,'commitMultiVoucher()');assert.equal(snapshot(updated),before);assert.equal(value(updated,'getAllTransactions().length'),3);});
 await test('Clock rollback is detected across persistent checkpoint',async()=>{await updated.w.RatibLicense.checkpoint();updated.setTime(base);assert.equal(updated.w.RatibLicense.current().state,'clock');assert.equal(updated.w.RatibLicense.current().writable,false);});
 await test('Annual activation, rejected tampering, and rejected foreign-device token',async()=>{updated.setTime(base+3*86400000+10);await activate(updated,{id:'LIC-year',issuedAt:base+3*86400000,serverAt:base+3*86400000});assert.equal(updated.w.RatibLicense.current().state,'annual');const req=await P.verifyRequest(await updated.w.RatibLicense.requestCode(''));const wrong=await signed('other-device',{issuedAt:base+3*86400000,serverAt:base+3*86400000});await assert.rejects(()=>updated.w.RatibLicense.accept(wrong));const valid=await signed(req.device,{id:'LIC-year',issuedAt:base+3*86400000,serverAt:base+3*86400000});const pieces=valid.split('.'),c=P.unpack(pieces[2]);c.kind='permanent';c.expiresAt=null;pieces[2]=P.pack(c);await assert.rejects(()=>updated.w.RatibLicense.accept(pieces.join('.')),/INVALID_SIGNATURE/);});
 await test('Signed revocation persists and cannot be rolled back with old token',async()=>{const old=await signed(device,{id:'LIC-year',issuedAt:base+3*86400000,serverAt:base+3*86400000});const revoked=await signed(device,{id:'LIC-year',revision:2,status:'revoked',issuedAt:base+3*86400000+1,serverAt:base+3*86400000+1});await updated.w.RatibLicense.accept(revoked);assert.equal(updated.w.RatibLicense.current().state,'revoked');await assert.rejects(()=>updated.w.RatibLicense.accept(old),/STALE_ACTIVATION_TOKEN/);});
 await test('Renewal restores edits only with newer signed revision',async()=>{await updated.w.RatibLicense.accept(await signed(device,{id:'LIC-year',revision:3,issuedAt:base+3*86400000+2,serverAt:base+3*86400000+2}));assert.equal(updated.w.RatibLicense.current().writable,true);});
 await test('Permanent offline license remains active beyond annual duration',async()=>{await activate(updated,{id:'LIC-permanent',kind:'permanent',expiresAt:null,issuedAt:base+3*86400000+2,serverAt:base+3*86400000+2});updated.setTime(base+4*365*86400000);assert.equal(updated.w.RatibLicense.current().writable,true);});
 await test('Financial persistence reset keeps separately stored license and device identity',async()=>{assert(!value(updated,'Object.keys(_snapshotMemStore()).join()').includes('ratib_license'));const before=await P.verifyRequest(await updated.w.RatibLicense.requestCode(''));await value(updated,'flushStorage();_replacePersistentData({})');value(updated,"_memStore.masar_plan={month:monthKey(),transactions:[]}");assert.equal((await P.verifyRequest(await updated.w.RatibLicense.requestCode(''))).device,before.device);assert.equal(updated.w.RatibLicense.current().state,'permanent');});
 const online=make({offline:false});await boot(online);await waitFor(()=>online.w.RatibLicense.current().writable,'server trial');
 await test('Online first use obtains trial and sends no financial data',async()=>{assert.equal(online.w.RatibLicense.current().state,'trial');assert(online.networkCalls.length>0);for(const req of online.networkCalls){const body=JSON.parse(req.body);assert.deepEqual(Object.keys(body),['requestCode']);assert(!req.body.includes('synthetic-1'));}});
 const setup=make({setup:true});await boot(setup);
 await test('Unconfigured review branch fails closed with visible explanation',async()=>{assert.equal(setup.w.RatibLicense.current().state,'setup');assert.equal(setup.w.RatibLicense.current().writable,false);assert(setup.w.document.getElementById('licenseReadOnlyBanner').textContent.includes('نسخة مراجعة'));});
 const sw=fs.readFileSync(root+'/sw.js','utf8');await test('Offline shell caches all license runtime files, retains scoped financial-independent cache',async()=>{for(const name of ['config.js','protocol.js','client.js','ui.css'])assert(sw.includes('./licensing/'+name));assert(sw.includes('self.registration.scope'));assert(!sw.includes('ratib_license_v1'));});
 console.log(JSON.stringify({passed:results.length,tests:results},null,2));
}catch(e){console.error(e.stack);for(const f of fixtures)if(f.logs.length||f.errors.length)console.error(JSON.stringify({errors:f.errors,logs:f.logs}));process.exitCode=1;}finally{fixtures.forEach(f=>f.w.close());}})();
