import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {DatabaseSync} from 'node:sqlite';
import worker from '../cloudflare/src/worker.mjs';
const P=globalThis.RatibLicenseProtocol,results=[],base=Date.UTC(2026,9,9,12);let clock=base,ip=0;const realNow=Date.now;Date.now=()=>clock;
class D1Statement{constructor(db,sql,args=[]){this.db=db;this.sql=sql;this.args=args;}bind(...args){return new D1Statement(this.db,this.sql,args);}async first(){return this.db.prepare(this.sql).get(...this.args)||null;}async all(){return {results:this.db.prepare(this.sql).all(...this.args)};}async run(){const r=this.db.prepare(this.sql).run(...this.args);return {success:true,meta:{changes:Number(r.changes)}};}}
class D1{constructor(){this.db=new DatabaseSync(':memory:');this.db.exec(readFileSync(new URL('../cloudflare/staging-schema.sql',import.meta.url),'utf8'));this.db.exec(readFileSync(new URL('../cloudflare/migrations/0001_signed_licensing.sql',import.meta.url),'utf8'));}prepare(sql){return new D1Statement(this.db,sql);}async batch(statements){this.db.exec('BEGIN');try{const results=[];for(const s of statements)results.push(await s.run());this.db.exec('COMMIT');return results;}catch(e){this.db.exec('ROLLBACK');throw e;}}}
const env={DB:new D1(),ADMIN_API_KEY:'synthetic-test-admin-only-not-a-deployed-secret',SIGNING_KEY_ENCRYPTION_KEY:'synthetic-test-wrap-only-not-a-deployed-secret',LICENSE_ISSUER:'https://license.test',ALLOWED_APP_ORIGINS:'["https://app.test"]'};
async function call(path,method='GET',value,auth=true,origin='https://license.test',fixedIp){const req=new Request('https://license.test'+path,{method,headers:{...(auth?{Authorization:'Bearer '+env.ADMIN_API_KEY}:{}),Origin:origin,'CF-Connecting-IP':fixedIp||'test-'+(++ip),...(value===undefined?{}:{'Content-Type':'application/json'})},body:value===undefined?undefined:JSON.stringify(value)});const response=await worker.fetch(req,env);let data;try{data=await response.json();}catch{data=null;}return {status:response.status,data,response};}
async function test(name,fn){await fn();results.push(name);console.log('PASS',name);}
async function identity(){const pair=await crypto.subtle.generateKey({name:'ECDSA',namedCurve:'P-256'},false,['sign','verify']),publicKey=P.publicJwk(await crypto.subtle.exportKey('jwk',pair.publicKey));return {publicKey,privateKey:pair.privateKey,device:await P.deviceId(publicKey)};}
const A=await identity(),B=await identity();let config,annual,permanent,token,trialToken;
async function create(kind,extras={}){const r=await call('/api/admin/licenses','POST',{license_type:kind,binding_type:'device',max_devices:1,custom_days:30,...extras});assert.equal(r.status,200,JSON.stringify(r.data));return r.data.id;}
async function issue(id,who=A,email='',verified=false){return call('/api/admin/licenses/'+id+'/issue','POST',{requestCode:await P.makeRequest(who,email),email_verified:verified});}
async function verify(code,who=A){return P.verifyToken(code,config,who.device);}
try{
 await test('Unauthorized administration and signing are rejected',async()=>{for(const p of ['/api/admin/licenses','/api/admin/signing/public','/api/admin/audit'])assert.equal((await call(p,'GET',undefined,false)).status,401);assert.equal((await call('/api/admin/signing/init','POST',{},false)).status,401);});
 await test('Cross-origin admin mutation rejected',async()=>assert.equal((await call('/api/admin/signing/init','POST',{},true,'https://evil.test')).status,403));
 await test('Signing key generated on server, encrypted at rest; public response excludes private key',async()=>{const r=await call('/api/admin/signing/init','POST',{});assert.equal(r.status,200);const row=env.DB.db.prepare('SELECT * FROM ratib_signing_keys').get();assert(!row.wrapped_private_jwk.includes('"d"'));const pub=await call('/api/admin/signing/public');config={issuer:env.LICENSE_ISSUER,publicKeys:pub.data.publicKeys};assert(!JSON.stringify(pub.data).includes('wrapped_private'));assert(!r.data.publicKey.d);});
 await test('Signing initialization idempotent and retains key',async()=>{const first=await call('/api/admin/signing/init','POST',{});const second=await call('/api/admin/signing/init','POST',{});assert.equal(first.data.kid,second.data.kid);assert.equal(env.DB.db.prepare('SELECT COUNT(*) n FROM ratib_signing_keys').get().n,1);});
 await test('Three-day trial starts at server time, unlimited voucher entitlement',async()=>{const r=await call('/api/trial','POST',{requestCode:await P.makeRequest(A)},false,'https://app.test');assert.equal(r.status,200,JSON.stringify(r.data));trialToken=r.data.token;const c=await verify(trialToken);assert.equal(c.kind,'trial');assert.equal(c.expiresAt-c.startsAt,3*86400000);assert.equal(P.status(c,clock).writable,true);assert.equal(c.startsAt,base);assert(!('voucherLimit' in c));});
 await test('Repeated trial request does not reset start date',async()=>{clock+=86400000;const r=await call('/api/trial','POST',{requestCode:await P.makeRequest(A)},false,'https://app.test');assert.equal((await verify(r.data.token)).startsAt,base);});
 await test('Trial expires exactly at day three, preserves record',async()=>{clock=base+3*86400000;assert.equal(P.status(await verify(trialToken),clock).state,'expired');const r=await call('/api/trial','POST',{requestCode:await P.makeRequest(A)},false,'https://app.test');assert.equal(P.status(await verify(r.data.token),clock).writable,false);assert.equal(env.DB.db.prepare('SELECT COUNT(*) n FROM ratib_trial_starts').get().n,1);clock=base;});
 await test('Annual license and device-only default are valid',async()=>{annual=await create('annual');const r=await issue(annual);assert.equal(r.status,200,JSON.stringify(r.data));token=r.data.token;const c=await verify(token);assert.equal(c.kind,'annual');assert.equal(c.binding,'device');assert.equal(c.maxDevices,1);assert.equal(c.email,'');assert.equal(new Date(c.expiresAt).getUTCFullYear(),2027);});
 await test('Offline signature verification needs no server call',async()=>assert.equal(P.status(await verify(token),clock).writable,true));
 await test('Token bound to a different device is rejected',async()=>assert.rejects(()=>verify(token,B),/INVALID_CLAIMS/));
 await test('Tampered token rejected',async()=>{const p=token.split('.'),c=P.unpack(p[2]);c.maxDevices=100;p[2]=P.pack(c);await assert.rejects(()=>verify(p.join('.')),/INVALID_SIGNATURE/);});
 await test('Unknown issuer key and issuer mismatch rejected',async()=>{await assert.rejects(()=>P.verifyToken(token,{issuer:env.LICENSE_ISSUER,publicKeys:{}},A.device),/UNKNOWN_SIGNING_KEY/);await assert.rejects(()=>P.verifyToken(token,{...config,issuer:'https://wrong.test'},A.device),/INVALID_CLAIMS/);});
 await test('Second device exceeds default device limit',async()=>assert.equal((await issue(annual,B)).status,409));
 await test('Raising device limit permits second device without erasing first',async()=>{assert.equal((await call('/api/admin/licenses/'+annual,'PATCH',{max_devices:2})).status,200);assert.equal((await issue(annual,B)).status,200);assert.equal((await call('/api/admin/licenses/'+annual+'/devices')).data.devices.length,2);});
 await test('Cannot shrink limit below active device count',async()=>assert.equal((await call('/api/admin/licenses/'+annual,'PATCH',{max_devices:1})).status,409));
 await test('Revoking a device returns signed revocation at next sync',async()=>{assert.equal((await call('/api/admin/licenses/'+annual+'/device','PATCH',{device_id:B.device,status:'revoked'})).status,200);const r=await call('/api/sync','POST',{requestCode:await P.makeRequest(B,'',crypto,annual)},false,'https://app.test');assert.equal(P.status(await verify(r.data.token,B),clock).state,'revoked');});
 await test('License transfer reuses freed slot',async()=>{const stopped=await call('/api/sync','POST',{requestCode:await P.makeRequest(B,'',crypto,annual)},false,'https://app.test');const before=await verify(stopped.data.token,B);await call('/api/admin/licenses/'+annual,'PATCH',{max_devices:1});await call('/api/admin/licenses/'+annual+'/device','PATCH',{device_id:A.device,status:'revoked'});const resumed=await issue(annual,B);assert.equal(resumed.status,200);const after=await verify(resumed.data.token,B);assert.equal(after.status,'active');assert(after.revision>before.revision,'A reactivated device must supersede its signed revocation');});
 await test('Permanent license has no expiry',async()=>{permanent=await create('permanent');const r=await issue(permanent);const c=await verify(r.data.token);assert.equal(c.expiresAt,null);assert.equal(P.status(c,clock+20*365*86400000).writable,true);});
 await test('Custom duration honored',async()=>{const id=await create('custom',{custom_days:7}),r=await issue(id);assert.equal((await verify(r.data.token)).expiresAt-clock,7*86400000);});
 await test('Email binding requires owner verification, not merely email text',async()=>{assert.equal((await call('/api/admin/licenses','POST',{license_type:'annual',binding_type:'email',email:'person@example.test',max_devices:2})).status,400);const id=await create('annual',{binding_type:'email',email:'person@example.test',email_verified:true,max_devices:2});assert.equal((await issue(id,A,'different@example.test')).status,403);const r=await issue(id,A,'person@example.test',true);assert.equal(r.status,200);const c=await verify(r.data.token);assert.equal(c.emailVerified,true);assert.equal(c.binding,'email');});
 await test('Email plus device binding retains both requirements',async()=>{const id=await create('annual',{binding_type:'both',email:'person@example.test',email_verified:true});const r=await issue(id,A,'person@example.test');assert.equal((await verify(r.data.token)).binding,'both');await assert.rejects(()=>verify(r.data.token,B));});
 await test('Stopping license yields signed stopped state; renewal reactivates with higher revision',async()=>{await call('/api/admin/licenses/'+permanent,'PATCH',{status:'revoked'});const stopped=await call('/api/sync','POST',{requestCode:await P.makeRequest(A,'',crypto,permanent)},false,'https://app.test');const c1=await verify(stopped.data.token);assert.equal(c1.status,'revoked');await call('/api/admin/licenses/'+permanent,'PATCH',{status:'active'});const resumed=await call('/api/sync','POST',{requestCode:await P.makeRequest(A,'',crypto,permanent)},false,'https://app.test');const c2=await verify(resumed.data.token);assert.equal(c2.status,'active');assert(c2.revision>c1.revision);});
 await test('Expired license rejects new issue; extension restores ability',async()=>{const id=await create('custom',{custom_days:1});clock+=2*86400000;assert.equal((await issue(id)).status,403);assert.equal((await call('/api/admin/licenses/'+id,'PATCH',{extend_days:7})).status,200);assert.equal((await issue(id)).status,200);clock=base;});
 await test('Invalid request signature and forged device hash rejected',async()=>{const code=await P.makeRequest(A),p=code.split('.'),req=P.unpack(p[1]);req.device=B.device;p[1]=P.pack(req);assert.equal((await call('/api/trial','POST',{requestCode:p.join('.')},false,'https://app.test')).status,400);});
 await test('New device cannot sync by knowing license ID without registration',async()=>{const C=await identity();assert.equal((await call('/api/sync','POST',{requestCode:await P.makeRequest(C,'',crypto,permanent)},false,'https://app.test')).status,403);});
 await test('Legacy licenses and active devices survive additive migration and consume limit',async()=>{const id='LIC-legacy';env.DB.db.prepare("INSERT INTO licenses(id,license_type,binding_type,max_devices,start_date,status) VALUES(?,'permanent','device',1,?,'active')").run(id,'2026-01-01 00:00:00');env.DB.db.prepare("INSERT INTO license_devices(id,license_id,device_id,status) VALUES('legacy-device',?,'previous-device','active')").run(id);assert.equal((await issue(id)).status,409);const list=await call('/api/admin/licenses/'+id+'/devices');assert.equal(list.data.legacyDevices.length,1);assert.equal((await call('/api/admin/licenses/'+id+'/device','PATCH',{device_id:'previous-device',status:'revoked',legacy:true})).status,200);assert.equal((await issue(id)).status,200);assert.equal(env.DB.db.prepare('SELECT COUNT(*) n FROM license_devices WHERE license_id=?').get(id).n,1);});
 await test('Competing new-device requests cannot exceed quota',async()=>{const id=await create('annual');const r=await Promise.all([issue(id,A),issue(id,B)]);assert.equal(r.filter(x=>x.status===200).length,1,JSON.stringify(r));assert.equal(r.filter(x=>x.status===409).length,1);});
 await test('Administrative audit contains no secrets or signed token text',async()=>{const r=await call('/api/admin/audit');assert(r.data.events.length>0);const text=JSON.stringify(r.data);assert(!text.includes(env.ADMIN_API_KEY));assert(!text.includes('RATIB1.'));assert(!text.includes('wrapped_private'));});
 await test('Persistent rate limiting blocks repeated unauthorized requests',async()=>{for(let i=0;i<30;i++)assert.equal((await call('/api/admin/licenses','GET',undefined,false,'https://license.test','same-ip')).status,401);assert.equal((await call('/api/admin/licenses','GET',undefined,false,'https://license.test','same-ip')).status,429);});
 await test('CORS limited to allowed app origin',async()=>{assert.equal((await call('/api/trial','POST',{requestCode:await P.makeRequest(A)},false,'https://evil.test')).status,403);const r=await call('/api/trial','POST',{requestCode:await P.makeRequest(A)},false,'https://app.test');assert.equal(r.response.headers.get('Access-Control-Allow-Origin'),'https://app.test');});
 console.log(JSON.stringify({passed:results.length,tests:results},null,2));
}finally{Date.now=realNow;env.DB.db.close();}
