export const adminPage=`<!doctype html><html lang="ar" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>راتب | إدارة التراخيص</title><style nonce="__NONCE__">
*{box-sizing:border-box}body{margin:0;padding:16px;background:#f8fafc;color:#0f172a;font:16px Tahoma,Arial,sans-serif}main{max-width:1150px;margin:auto}section{background:white;padding:20px;border:1px solid #cbd5e1;border-radius:14px;margin:16px 0}h1{color:#0284c7}h2{font-size:19px}label{display:block;margin:8px 0;font-weight:bold}input,select,textarea{width:100%;padding:12px;border:1px solid #cbd5e1;border-radius:8px;font:inherit}textarea{direction:ltr;resize:vertical;min-height:110px;overflow-wrap:anywhere}button{cursor:pointer;background:#0284c7;color:white;border:0;border-radius:8px;min-height:44px;padding:10px 15px;font:inherit;margin:5px 3px}button:disabled{opacity:.5}.sub{background:#e2e8f0;color:#0f172a}.danger{background:#b91c1c}.row{display:grid;grid-template-columns:repeat(auto-fit,minmax(190px,1fr));gap:12px}.tablewrap{overflow:auto}table{width:100%;border-collapse:collapse;font-size:14px}th,td{border-bottom:1px solid #cbd5e1;padding:12px;text-align:right;vertical-align:top}td.actions{min-width:240px}th{background:#f1f5f9}small,p{line-height:1.7}#message{white-space:pre-wrap;position:sticky;top:0;background:#e0f2fe;padding:12px;border-radius:8px;z-index:2}label.check{display:flex;gap:8px;font-weight:normal}label.check input{width:22px}code{overflow-wrap:anywhere}details{margin:14px 0}[hidden]{display:none!important}
</style></head><body><main><h1>إدارة تراخيص راتب</h1><p>إصدار تفعيل موقّع لجهاز معروف من رمز طلبه. التوقيع الخاص يبقى في Cloudflare، ولا يحتوي رمز الطلب على بيانات محاسبية.</p><p id="message" role="status" aria-live="polite">أدخل مفتاح الإدارة للاتصال.</p>
<section><label for="adminKey">مفتاح الإدارة</label><input type="password" id="adminKey" autocomplete="off"><button id="load">عرض التراخيص</button><button id="logout" class="sub">إنهاء الجلسة</button><small>المفتاح يبقى في ذاكرة هذه الصفحة فقط، ويُمسح عند إنهاء الجلسة أو إعادة تحميلها.</small></section>
<section><h2>إصدار ترخيص جديد</h2><div class="row"><label>نوع الترخيص<select id="kind"><option value="trial">تجريبي — 3 أيام</option><option value="annual">سنوي</option><option value="permanent">دائم</option><option value="custom">مدة مخصصة</option></select></label><label id="customBox" hidden>عدد الأيام<input id="days" type="number" min="1" max="3650" value="30"></label><label>طريقة الربط<select id="binding"><option value="device">جهاز فقط — بدون بريد</option><option value="email">بريد إلكتروني مع حد الأجهزة</option><option value="both">بريد وجهاز معًا</option></select></label><label>البريد<input id="email" type="email" maxlength="254"></label><label>الحد الأقصى للأجهزة<input id="max" type="number" min="1" max="100" value="1"></label></div><label class="check" id="verifiedLabel" hidden><input type="checkbox" id="verified">تحققت كمالك من هوية صاحب البريد خارج التطبيق؛ كتابة البريد وحدها ليست إثباتًا لملكيته.</label><button id="create">إنشاء الترخيص</button></section>
<section><h2>التراخيص المسجلة</h2><label>عرض الحالة<select id="filter"><option value="all">الجميع</option><option value="active">نشط</option><option value="expired">منتهٍ</option><option value="revoked">موقوف</option></select></label><div id="result" class="tablewrap">لم يتم تحميل التراخيص بعد.</div></section>
<section id="deviceSection" hidden><h2>أجهزة الترخيص</h2><p id="selectedLicense"></p><div id="devices" class="tablewrap"></div><label for="requestCode">رمز طلب التفعيل المنسوخ من جهاز المستخدم</label><textarea id="requestCode" maxlength="10000" spellcheck="false"></textarea><label class="check"><input type="checkbox" id="confirmEmail">عند ربط البريد: تحققت من صاحب البريد ومطابقته لطلب هذا الجهاز.</label><button id="issue">إصدار رمز لهذا الجهاز</button><label for="activationToken">رمز الاستجابة لتسليمه إلى المستخدم</label><textarea id="activationToken" readonly spellcheck="false"></textarea><button id="copyToken" class="sub">نسخ رمز التفعيل</button><p>عند نقل الترخيص: ألغ ارتباط الجهاز القديم أولًا، ثم أصدر رمزًا لطلب الجهاز الجديد. زيادة حد الأجهزة تحفظ ارتباط الأجهزة الحالية. إلغاء جهاز أو ترخيص يظهر لديه عند اتصاله التالي.</p></section>
<section><h2>سجل الإدارة</h2><button id="audit" class="sub">عرض آخر العمليات</button><div id="auditResult" class="tablewrap"></div></section>
<details><summary>إعداد التوقيع — للبيئة التجريبية قبل الدمج</summary><section><p>ينشئ الزر مفتاح التوقيع داخل Cloudflare مرة واحدة، بعد إعداد سر تشفير المفاتيح. لا يصدر المفتاح الخاص ولا يستبدل المفتاح الموجود.</p><button id="initialize">تهيئة التوقيع</button><button id="publicKey" class="sub">عرض مفاتيح التحقق العامة</button><textarea id="publicKeys" readonly></textarea><p>أدرج المفاتيح العامة فقط في إعدادات التطبيق قبل اختبار التفعيل. لا تنشر هذا الفرع على main قبل الاعتماد.</p></section></details>
</main><script nonce="__NONCE__">
const el=id=>document.getElementById(id),message=t=>el('message').textContent=t;let key='',items=[],selected='';
const errors={UNAUTHORIZED:'مفتاح الإدارة غير صحيح.',RATE_LIMITED:'طلبات كثيرة. انتظر دقيقة ثم أعد المحاولة.',DEVICE_LIMIT_REACHED:'تم بلوغ حد الأجهزة. ألغ ارتباط جهاز قديم أو زد الحد.',EMAIL_MISMATCH_OR_UNVERIFIED:'البريد غير مطابق أو لم يؤكد المالك التحقق منه.',OWNER_EMAIL_VERIFICATION_REQUIRED:'أكد التحقق من هوية صاحب البريد أولًا.',LICENSE_EXPIRED:'الترخيص منتهٍ. مدده قبل إصدار الرمز.',LICENSE_REVOKED:'الترخيص موقوف.',SIGNING_KEY_NOT_INITIALIZED:'هيئ مفتاح التوقيع أولًا.',SIGNING_WRAP_SECRET_REQUIRED:'أضف سر SIGNING_KEY_ENCRYPTION_KEY في إعدادات Cloudflare أولًا.',LIMIT_BELOW_ACTIVE_DEVICES:'العدد المطلوب أقل من الأجهزة النشطة.',SERVICE_ERROR:'تعذر تنفيذ العملية. راجع إعدادات البيئة التجريبية وقاعدة البيانات.'};
async function api(path,method='GET',body){if(el('adminKey').value){key=el('adminKey').value;el('adminKey').value='';}if(!key)throw Error('أدخل مفتاح الإدارة أولًا.');const res=await fetch(path,{method,headers:{Authorization:'Bearer '+key,...(body===undefined?{}:{'Content-Type':'application/json'})},body:body===undefined?undefined:JSON.stringify(body),cache:'no-store'}),data=await res.json();if(!res.ok)throw Error(errors[data.error]||data.error||'تعذر الاتصال.');return data;}
async function run(fn){const buttons=[...document.querySelectorAll('button')];buttons.forEach(b=>b.disabled=true);try{await fn();}catch(e){message(e.message);}finally{buttons.forEach(b=>b.disabled=false);}}
const types={trial:'تجريبي',annual:'سنوي',permanent:'دائم',custom:'مخصص'},bindings={device:'جهاز',email:'بريد مع حد الأجهزة',both:'بريد وجهاز'},statuses={active:'نشط',revoked:'موقوف',expired:'منتهٍ'};
function status(l){return l.status==='revoked'?'revoked':l.expiry_date&&Date.parse(l.expiry_date.replace(' ','T')+'Z')<=Date.now()?'expired':'active';}
function button(label,action,style='sub'){const b=document.createElement('button');b.textContent=label;b.className=style;b.type='button';b.addEventListener('click',()=>run(action));return b;}
function table(headers,rows){const t=document.createElement('table'),h=document.createElement('tr');headers.forEach(x=>{const c=document.createElement('th');c.textContent=x;h.append(c)});t.append(h);rows.forEach(fields=>{const row=document.createElement('tr');fields.forEach(x=>{const c=document.createElement('td');if(x instanceof Node){c.className='actions';c.append(x)}else c.textContent=String(x??'—');row.append(c)});t.append(row)});return t;}
async function refresh(){items=(await api('/api/admin/licenses')).licenses;render();message('تم تحميل '+items.length+' ترخيص.');}
function render(){const rows=items.filter(l=>el('filter').value==='all'||status(l)===el('filter').value).map(l=>{const actions=document.createElement('div');actions.append(button('الأجهزة والتفعيل',()=>showDevices(l.id)),button(l.status==='revoked'?'إعادة التنشيط':'إيقاف',async()=>{if(!confirm('تأكيد تغيير حالة الترخيص؟'))return;await api('/api/admin/licenses/'+l.id,'PATCH',{status:l.status==='revoked'?'active':'revoked'});await refresh();},l.status==='revoked'?'sub':'danger'),button('حد الأجهزة',async()=>{const x=prompt('عدد الأجهزة (1 إلى 100)',l.max_devices);if(x===null)return;await api('/api/admin/licenses/'+l.id,'PATCH',{max_devices:Number(x)});await refresh();}),button('تغيير النوع والمدة',async()=>{const type=prompt('النوع: annual أو permanent أو custom أو trial',l.license_type);if(type===null)return;let days;if(type==='custom'){days=prompt('عدد الأيام','30');if(days===null)return;}if(!confirm('تغيير النوع وإعادة حساب المدة من اليوم؟'))return;await api('/api/admin/licenses/'+l.id,'PATCH',{license_type:type,custom_days:Number(days)});await refresh();}));if(l.license_type!=='permanent')actions.append(button('تمديد',async()=>{const x=prompt('عدد أيام التمديد','365');if(x===null)return;await api('/api/admin/licenses/'+l.id,'PATCH',{extend_days:Number(x)});await refresh();}));return [l.id,types[l.license_type],l.email||'—',bindings[l.binding_type],l.active_devices+' / '+l.max_devices,l.start_date,l.expiry_date||'دائم',statuses[status(l)],actions]});el('result').replaceChildren(table(['الترخيص','النوع','البريد','الربط','الأجهزة','البداية UTC','النهاية UTC','الحالة','الإجراءات'],rows));}
async function showDevices(id){selected=id;el('selectedLicense').textContent=id;el('deviceSection').hidden=false;el('activationToken').value='';const data=await api('/api/admin/licenses/'+id+'/devices');const rows=[...data.devices.map(d=>({...d,legacy:false})),...data.legacyDevices.map(d=>({...d,device_id:String(d.device_id??d.id),legacy:true}))].map(d=>{const box=document.createElement('div');if(d.status==='active')box.append(button('إلغاء الارتباط',async()=>{if(!confirm('تأكيد إلغاء ارتباط هذا الجهاز؟'))return;await api('/api/admin/licenses/'+id+'/device','PATCH',{device_id:d.device_id,status:'revoked',legacy:d.legacy});await showDevices(id);await refresh();},'danger'));return [d.device_id,d.legacy?'ارتباط سابق':'موقّع',statuses[d.status]||d.status,box]});el('devices').replaceChildren(table(['الجهاز','المصدر','الحالة','الإجراء'],rows));el('deviceSection').scrollIntoView({block:'start'});}
el('load').onclick=()=>run(refresh);el('logout').onclick=()=>{key='';selected='';items=[];el('adminKey').value='';el('activationToken').value='';el('requestCode').value='';el('publicKeys').value='';el('result').textContent='انتهت جلسة الإدارة.';el('auditResult').replaceChildren();el('deviceSection').hidden=true;message('تم مسح مفتاح الإدارة من الذاكرة.');};
el('kind').onchange=()=>el('customBox').hidden=el('kind').value!=='custom';el('binding').onchange=()=>{el('verifiedLabel').hidden=el('binding').value==='device';el('verified').checked=false;};el('filter').onchange=render;
el('create').onclick=()=>run(async()=>{if(!confirm('إنشاء هذا الترخيص؟'))return;const result=await api('/api/admin/licenses','POST',{license_type:el('kind').value,binding_type:el('binding').value,email:el('email').value.trim(),max_devices:Number(el('max').value),custom_days:Number(el('days').value),email_verified:el('verified').checked});await refresh();await showDevices(result.id);message('أنشئ الترخيص. ألصق طلب الجهاز لإصدار رمز التفعيل.');});
el('issue').onclick=()=>run(async()=>{if(!selected)throw Error('اختر الترخيص أولًا.');const result=await api('/api/admin/licenses/'+selected+'/issue','POST',{requestCode:el('requestCode').value.trim(),email_verified:el('confirmEmail').checked});el('activationToken').value=result.token;await refresh();message('صدر رمز موقّع لهذا الجهاز؛ انسخه وسلمه إلى صاحبه.');});
el('copyToken').onclick=()=>run(async()=>{if(!el('activationToken').value)throw Error('لم يصدر رمز بعد.');await navigator.clipboard.writeText(el('activationToken').value);message('تم نسخ رمز التفعيل.');});
el('audit').onclick=()=>run(async()=>{const events=(await api('/api/admin/audit')).events;el('auditResult').replaceChildren(table(['التاريخ UTC','العملية','الترخيص','الجهاز','التفاصيل'],events.map(x=>[new Date(x.created_at).toISOString(),x.action,x.license_id,x.device_id,x.details])));message('السجل لا يحتوي مفاتيح الإدارة أو التوقيع أو بيانات المستخدم المحاسبية.');});
el('initialize').onclick=()=>run(async()=>{if(!confirm('تهيئة مفتاح التوقيع داخل بيئة Cloudflare الحالية؟'))return;await api('/api/admin/signing/init','POST',{});el('publicKeys').value=JSON.stringify(await api('/api/admin/signing/public'),null,2);message('التوقيع جاهز. اعتمد مفاتيح التحقق العامة في النسخة التجريبية.');});el('publicKey').onclick=()=>run(async()=>el('publicKeys').value=JSON.stringify(await api('/api/admin/signing/public'),null,2));
window.addEventListener('pagehide',()=>{key='';el('adminKey').value='';});
</script></body></html>`;
